#!/bin/bash

# Author: Bob Kraemer
# Date Created: 09/26/2024
# Last Modified: 09/26/2024

# Description
# Prints "This is my first script" to the terminal

# Usage
# our_first_script

echo "This is my first script"
exit 0
